on: [push, pull_request]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

name: Deploy NextJS
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install --prefix nextjs-testapp
      - name: Build NextJS
        run: npm run export --prefix nextjs-testapp
      - name: Deploy to s3
        uses: eisberg-labs/static-website-to-s3@main
        with:
          target: nextjs-testapp/out
          dest: next-to-s3/nextjs-testapp
          exclusions: ^nextjs-testapp\/out\/(index).html$
          bucket: ${{ secrets.BUCKET }}
